sudo: required

env:
    - BUILDENV=travis

services:
    - docker

language: go

go:
    - 1.x

before_install:
    - sudo service postgresql stop
    - |
        docker run -d --name buildgraph-postgresql -p 5432:5432 \
        -e 'POSTGRES_USER=buildgraph' \
        -e 'POSTGRES_PASSWORD=password' \
        -e 'POSTGRES_DB=buildgraph' \
        --restart=always \
        postgres:10
    - |
        docker run -d --name gitlab-postgresql \
        -e 'DB_NAME=gitlabhq_production' \
        -e 'DB_USER=gitlab' \
        -e 'DB_PASS=password' \
        -e 'DB_EXTENSION=pg_trgm' \
        --restart=always \
        sameersbn/postgresql:9.6-2
    - |
        docker run -d --name gitlab-redis sameersbn/redis:latest
    - |
        docker run -d --name gitlab -p 10080:80 \
        --link gitlab-postgresql:postgresql \
        --link gitlab-redis:redisio \
        -e 'GITLAB_PORT=10080' \
        -e 'GITLAB_SSH_PORT=10022' \
        -e 'GITLAB_SECRETS_DB_KEY_BASE=secret' \
        -e 'GITLAB_SECRETS_SECRET_KEY_BASE=secret' \
        -e 'GITLAB_SECRETS_OTP_KEY_BASE=secret' \
        -e 'GITLAB_ROOT_PASSWORD=password' \
        --restart=always \
        sameersbn/gitlab:10.2.2
    - go get github.com/go-playground/overalls
    - go get -v -u -t ./...
    - docker ps
    - sleep 120

script:
    - make test

after_sucess:
    - go get github.com/mattn/goveralls
    - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
