version: '3.2'
services:
    postgres:
        image: postgres:10
        environment:
            POSTGRES_USER: buildgraph
            POSTGRES_PASSWORD: buildgraph
            POSTGRES_DB: buildgraph
        network_mode: 'host'
        ports:
            - '5432:5432'

    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        hostname: 'localhost'
        restart: 'always'
        network_mode: 'host'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost'
                gitlab_rails['initial_root_password'] = "password"
            GITLAB_SKIP_PG_UPGRADE: 'true'
        ports:
            - '8080:80'
            - '8443:443'
