storage:
    postgres:
        endpoint: localhost:5432
        user: buildgraph
        password: password
        database: buildgraph
webserver:
    endpoint: 192.168.1.100:1988
projects:
    namespace1:
        - project1
    namespace2:
        - project1
        - project2
    namespace3:
        - project1
